-- OPC 公司经营合规助手核心表（PostgreSQL）。
-- 回滚策略：关闭功能开关并保留数据；禁止在线 DROP/TRUNCATE。

CREATE TABLE IF NOT EXISTS xy_enterprise_profile (id bigserial PRIMARY KEY, opc_entity_id bigint NOT NULL DEFAULT 0, version integer NOT NULL DEFAULT 1, profile_json jsonb NOT NULL, source varchar(32) NOT NULL DEFAULT 'user', status varchar(16) NOT NULL DEFAULT 'draft', change_reason varchar(500) NOT NULL DEFAULT '', confirmed_by bigint NOT NULL DEFAULT 0, confirmed_at bigint NOT NULL DEFAULT 0, deleted smallint NOT NULL DEFAULT 0, create_time bigint NOT NULL DEFAULT 0, update_time bigint NOT NULL DEFAULT 0, CONSTRAINT uk_profile_version UNIQUE (opc_entity_id, version));
CREATE INDEX IF NOT EXISTS idx_profile_active ON xy_enterprise_profile (opc_entity_id, status, deleted);

CREATE TABLE IF NOT EXISTS xy_compliance_rule (id bigserial PRIMARY KEY, rule_code varchar(64) NOT NULL, rule_type varchar(20) NOT NULL DEFAULT 'task', name varchar(128) NOT NULL DEFAULT '', enabled smallint NOT NULL DEFAULT 1, deleted smallint NOT NULL DEFAULT 0, create_time bigint NOT NULL DEFAULT 0, update_time bigint NOT NULL DEFAULT 0, CONSTRAINT uk_rule_code UNIQUE (rule_code));
CREATE INDEX IF NOT EXISTS idx_rule_type_enabled ON xy_compliance_rule (rule_type, enabled, deleted);

CREATE TABLE IF NOT EXISTS xy_compliance_rule_version (id bigserial PRIMARY KEY, rule_id bigint NOT NULL DEFAULT 0, version integer NOT NULL DEFAULT 1, region_code varchar(16) NOT NULL DEFAULT 'CN-BJ', condition_json jsonb NOT NULL, action_json jsonb NOT NULL, status varchar(16) NOT NULL DEFAULT 'draft', effective_from bigint NOT NULL DEFAULT 0, effective_to bigint NOT NULL DEFAULT 0, created_by bigint NOT NULL DEFAULT 0, reviewed_by bigint NOT NULL DEFAULT 0, published_at bigint NOT NULL DEFAULT 0, create_time bigint NOT NULL DEFAULT 0, update_time bigint NOT NULL DEFAULT 0, CONSTRAINT uk_rule_version UNIQUE (rule_id, version));
CREATE INDEX IF NOT EXISTS idx_rule_version_active ON xy_compliance_rule_version (rule_id, status, effective_from, effective_to);

CREATE TABLE IF NOT EXISTS xy_enterprise_compliance_task (id bigserial PRIMARY KEY, opc_entity_id bigint NOT NULL DEFAULT 0, member_id bigint NOT NULL DEFAULT 0, rule_version_id bigint NOT NULL DEFAULT 0, period_key varchar(16) NOT NULL DEFAULT '', trigger_key varchar(64) NOT NULL DEFAULT 'periodic', task_type varchar(32) NOT NULL DEFAULT 'general', title varchar(160) NOT NULL DEFAULT '', description text, snapshot_json jsonb NOT NULL, material_json jsonb NOT NULL, status varchar(24) NOT NULL DEFAULT 'not_started', priority varchar(16) NOT NULL DEFAULT 'medium', due_at bigint NOT NULL DEFAULT 0, completed_at bigint NOT NULL DEFAULT 0, completion_note varchar(1000) NOT NULL DEFAULT '', deleted smallint NOT NULL DEFAULT 0, create_time bigint NOT NULL DEFAULT 0, update_time bigint NOT NULL DEFAULT 0, CONSTRAINT uk_task_idempotency UNIQUE (opc_entity_id, rule_version_id, period_key, trigger_key));
CREATE INDEX IF NOT EXISTS idx_task_member_status_due ON xy_enterprise_compliance_task (member_id, status, due_at);

CREATE TABLE IF NOT EXISTS xy_task_reminder (id bigserial PRIMARY KEY, task_id bigint NOT NULL DEFAULT 0, channel varchar(20) NOT NULL DEFAULT 'in_app', planned_at bigint NOT NULL DEFAULT 0, status varchar(24) NOT NULL DEFAULT 'pending', attempts integer NOT NULL DEFAULT 0, last_error varchar(1000) NOT NULL DEFAULT '', sent_at bigint NOT NULL DEFAULT 0, create_time bigint NOT NULL DEFAULT 0, update_time bigint NOT NULL DEFAULT 0, CONSTRAINT uk_reminder_idempotency UNIQUE (task_id, channel, planned_at));
CREATE INDEX IF NOT EXISTS idx_reminder_dispatch ON xy_task_reminder (status, planned_at);

CREATE TABLE IF NOT EXISTS xy_business_document (id bigserial PRIMARY KEY, opc_entity_id bigint NOT NULL DEFAULT 0, member_id bigint NOT NULL DEFAULT 0, attachment_id bigint NOT NULL DEFAULT 0, period_key varchar(16) NOT NULL DEFAULT '', document_type varchar(32) NOT NULL DEFAULT 'unknown', process_status varchar(24) NOT NULL DEFAULT 'uploaded', file_hash char(64) NOT NULL DEFAULT '', extracted_json jsonb, confidence numeric(5,4) NOT NULL DEFAULT 0, confirmed_by bigint NOT NULL DEFAULT 0, confirmed_at bigint NOT NULL DEFAULT 0, deleted smallint NOT NULL DEFAULT 0, create_time bigint NOT NULL DEFAULT 0, update_time bigint NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_document_opc_period ON xy_business_document (opc_entity_id, period_key, document_type);
CREATE INDEX IF NOT EXISTS idx_document_hash ON xy_business_document (opc_entity_id, file_hash);

CREATE TABLE IF NOT EXISTS xy_document_relation (id bigserial PRIMARY KEY, document_id bigint NOT NULL DEFAULT 0, relation_type varchar(24) NOT NULL DEFAULT '', relation_id bigint NOT NULL DEFAULT 0, create_time bigint NOT NULL DEFAULT 0, CONSTRAINT uk_document_relation UNIQUE (document_id, relation_type, relation_id));
CREATE INDEX IF NOT EXISTS idx_relation_target ON xy_document_relation (relation_type, relation_id);

CREATE TABLE IF NOT EXISTS xy_risk_event (id bigserial PRIMARY KEY, opc_entity_id bigint NOT NULL DEFAULT 0, member_id bigint NOT NULL DEFAULT 0, rule_version_id bigint NOT NULL DEFAULT 0, period_key varchar(16) NOT NULL DEFAULT '', severity varchar(16) NOT NULL DEFAULT 'medium', status varchar(16) NOT NULL DEFAULT 'open', summary varchar(500) NOT NULL DEFAULT '', evidence_json jsonb NOT NULL, resolution_note varchar(1000) NOT NULL DEFAULT '', first_hit_at bigint NOT NULL DEFAULT 0, last_hit_at bigint NOT NULL DEFAULT 0, resolved_at bigint NOT NULL DEFAULT 0, deleted smallint NOT NULL DEFAULT 0, create_time bigint NOT NULL DEFAULT 0, update_time bigint NOT NULL DEFAULT 0, CONSTRAINT uk_risk_period UNIQUE (opc_entity_id, rule_version_id, period_key));
CREATE INDEX IF NOT EXISTS idx_risk_member_status ON xy_risk_event (member_id, status, severity);

CREATE TABLE IF NOT EXISTS xy_compliance_monthly_report (id bigserial PRIMARY KEY, opc_entity_id bigint NOT NULL DEFAULT 0, member_id bigint NOT NULL DEFAULT 0, period_key varchar(16) NOT NULL DEFAULT '', version integer NOT NULL DEFAULT 1, status varchar(16) NOT NULL DEFAULT 'draft', statistics_json jsonb NOT NULL, completeness_json jsonb NOT NULL, risk_snapshot_json jsonb NOT NULL, content text, rule_versions_json jsonb NOT NULL, ai_model varchar(64) NOT NULL DEFAULT '', knowledge_version varchar(64) NOT NULL DEFAULT '', published_by bigint NOT NULL DEFAULT 0, published_at bigint NOT NULL DEFAULT 0, create_time bigint NOT NULL DEFAULT 0, update_time bigint NOT NULL DEFAULT 0, CONSTRAINT uk_report_version UNIQUE (opc_entity_id, period_key, version));
CREATE INDEX IF NOT EXISTS idx_report_member_period ON xy_compliance_monthly_report (member_id, period_key, status);

CREATE TABLE IF NOT EXISTS xy_service_ticket (id bigserial PRIMARY KEY, opc_entity_id bigint NOT NULL DEFAULT 0, member_id bigint NOT NULL DEFAULT 0, ticket_type varchar(32) NOT NULL DEFAULT 'compliance_review', status varchar(24) NOT NULL DEFAULT 'submitted', title varchar(160) NOT NULL DEFAULT '', description text, task_id bigint NOT NULL DEFAULT 0, risk_event_id bigint NOT NULL DEFAULT 0, assignee_id bigint NOT NULL DEFAULT 0, provider_name varchar(160) NOT NULL DEFAULT '', sla_due_at bigint NOT NULL DEFAULT 0, completed_at bigint NOT NULL DEFAULT 0, deleted smallint NOT NULL DEFAULT 0, create_time bigint NOT NULL DEFAULT 0, update_time bigint NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_ticket_member_status ON xy_service_ticket (member_id, status);

CREATE TABLE IF NOT EXISTS xy_service_ticket_record (id bigserial PRIMARY KEY, ticket_id bigint NOT NULL DEFAULT 0, from_status varchar(24) NOT NULL DEFAULT '', to_status varchar(24) NOT NULL DEFAULT '', content text, attachment_id bigint NOT NULL DEFAULT 0, operator_type varchar(16) NOT NULL DEFAULT 'member', operator_id bigint NOT NULL DEFAULT 0, create_time bigint NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_ticket_record ON xy_service_ticket_record (ticket_id, create_time);

CREATE TABLE IF NOT EXISTS xy_ai_audit_log (id bigserial PRIMARY KEY, opc_entity_id bigint NOT NULL DEFAULT 0, scene varchar(32) NOT NULL DEFAULT '', prompt_version varchar(32) NOT NULL DEFAULT '', model_name varchar(64) NOT NULL DEFAULT '', input_digest varchar(128) NOT NULL DEFAULT '', output_digest varchar(128) NOT NULL DEFAULT '', duration_ms integer NOT NULL DEFAULT 0, status varchar(16) NOT NULL DEFAULT 'success', error_message varchar(500) NOT NULL DEFAULT '', confirmed_by bigint NOT NULL DEFAULT 0, confirmed_at bigint NOT NULL DEFAULT 0, create_time bigint NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_ai_audit_opc_scene ON xy_ai_audit_log (opc_entity_id, scene, create_time);

